<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GioHang.aspx.cs" Inherits="BaiTapNhom_IS358L.GioHang" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Shop</title>
    <link href="css/style.css" rel="stylesheet" />
    
    <style type="text/css">
        .dtl{
            margin:auto;
        }
        .auto-style2, sup {
            color: #FF0000;
        }
        .td,input {
            font-family:Cambria;
            text-align:center;
            padding:5px;
            margin:5px;
            vertical-align:top;
            font-size: 18px;
            font-weight: bold;
        }
        .auto-style3 {
            text-align: center;
        }
        .auto-style4 {
            font-size: x-large;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server"> 
        <div id="header">
        <!-- begin nav bar -->
        <ul id="nav">
          <li><a href="Shop.aspx">Home</a></li>
          <li><a href="#">Áo</a>
              <ul class="subnav">
              <li><a href="GioiThieuSanPham.aspx?Loai=AT">Áo Thun</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=ASM">Áo Sơ Mi</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=AA">Áo Ấm</a></li>
            </ul>
          </li>
          <li><a href="#">Quần</a>
              <ul class="subnav">
              <li><a href="GioiThieuSanPham.aspx?Loai=QS">Quần Short</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=QTT">Quần Thẻ Thao</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=QT">Quần Tây</a></li>
            </ul>
          </li>
          <li><a href="#">Váy</a>
              <ul class="subnav">
              <li><a href="GioiThieuSanPham.aspx?Loai=VN">Váy Ngắn</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=VD">Váy Dài</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=VK">Khác</a></li>
            </ul>
          </li>
          <li><a href="#">Mũ</a></li>                 
          <li>
            <a href="#">
              Sản Phẩm Khác             
            </a>
            <ul class="subnav">
              <li><a href="GioiThieuSanPham.aspx?Loai=DC">Dây Chuyền</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=VT">Vòng Tay</a></li>
              <li><a href="GioiThieuSanPham.aspx?Loai=K">Khác</a></li>
            </ul>
          </li>
             <li><a href="GioHang.aspx">Giỏ Hàng <asp:Label ID="SLSP" runat="server"></asp:Label>
                 </a></li>
        </ul>
        <!-- End nav bar -->

        <!--  Begin user -->
            <%if (Session["user"] != null)
                { %>
                    <div id="user">
                        <a id="user-link" href="#">
                            <img id="user-img" src="/img/icons8-user-40.png" alt="" />    
                        <div id="username">
                            <%=FullName%> 
                        </div>
                        </a>
                        <asp:ImageButton ID="imgbtn_logout" runat="server" OnClick="imgbtn_logout_Click"  ImageUrl="/img/TrangChu/icons8-logout-40.png" />
                    </div>
            <% }
                else
                { %>                                                              
                    <asp:ImageButton ID="imgbtn_DN" runat="server" OnClick="imgbtn_DN_Click"  ImageUrl="/img/TrangChu/icons8-login-40.png" />                                                                                                                                        
            <%} %>
          <!--End user -->
      </div>
       
        <br/>
        <br/>
        <br/>

        <div>
            <br/>
            <div class="auto-style4"><strong><asp:Label ID="Label3" runat="server" Text="Thông tin giỏ hàng"></asp:Label></strong></div>
           <asp:GridView ID="GridView1" runat="server" Width="100%" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="MaSp" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <AlternatingRowStyle BackColor="White" />
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" HorizontalAlign="Left" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
            <br />
            <div class="auto-style3">
                <strong>
                <asp:Label ID="Label1" runat="server" Text="Tổng tiền: "></asp:Label>
                <asp:Label ID="Label2" runat="server" CssClass="auto-style2"></asp:Label><sup>đ</sup>
                <br />
                <asp:Button ID="btn" runat="server" Text="Thanh toán" OnClick="btn_Click" />
                </strong>

        </div>
     </div>
    </form>
</body>
    
</html>
